<?php

use Illuminate\Database\Seeder;

class MyMenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => '控制面板',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-02-11 14:24:41',
                'updated_at' => '2019-03-01 12:23:56',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => '媒體管理員',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2019-02-11 14:24:41',
                'updated_at' => '2019-02-26 08:28:47',
                'route' => 'voyager.media.index',
                'parameters' => 'null',
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => '使用者',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-02-11 14:24:41',
                'updated_at' => '2019-05-30 20:25:31',
                'route' => 'voyager.users.index',
                'parameters' => 'null',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => '角色',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 3,
                'order' => 2,
                'created_at' => '2019-02-11 14:24:41',
                'updated_at' => '2019-07-31 09:14:01',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => '工具',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2019-02-11 14:24:41',
                'updated_at' => '2019-08-16 16:24:10',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => '選單管理',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2019-02-11 14:24:41',
                'updated_at' => '2019-03-07 00:46:16',
                'route' => 'voyager.menus.index',
                'parameters' => 'null',
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => '資料庫',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2019-02-11 14:24:41',
                'updated_at' => '2019-02-26 08:28:47',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => '指南針',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2019-02-11 14:24:41',
                'updated_at' => '2019-02-26 08:28:47',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2019-02-11 14:24:41',
                'updated_at' => '2019-02-26 08:28:47',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => '設定',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 6,
                'created_at' => '2019-02-11 14:24:41',
                'updated_at' => '2019-02-26 08:28:47',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 7,
                'created_at' => '2019-02-11 14:24:41',
                'updated_at' => '2019-02-26 08:28:47',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => '文章集',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2019-02-11 14:49:57',
                'updated_at' => '2019-08-16 16:24:10',
                'route' => 'voyager.articles.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => '分類集',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2019-02-11 14:50:46',
                'updated_at' => '2019-08-16 16:24:10',
                'route' => 'voyager.cgys.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => '留言集',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bubble',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2019-02-11 14:52:14',
                'updated_at' => '2019-08-16 16:24:10',
                'route' => 'voyager.comments.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => '聯絡單集',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-mail',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2019-02-11 14:53:06',
                'updated_at' => '2019-08-16 16:24:10',
                'route' => 'voyager.contacts.index',
                'parameters' => 'null',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => '網頁元素集',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-puzzle',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-02-11 14:57:08',
                'updated_at' => '2019-08-16 16:24:10',
                'route' => 'voyager.elements.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => '多媒體集',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-photos',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-02-11 14:57:58',
                'updated_at' => '2019-08-16 16:24:10',
                'route' => 'voyager.medias.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => '合作夥伴集',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-trophy',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2019-02-11 15:01:08',
                'updated_at' => '2019-08-16 16:24:10',
                'route' => 'voyager.partners.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => '標籤集',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2019-02-11 15:04:01',
                'updated_at' => '2019-08-16 16:24:10',
                'route' => 'voyager.tags.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 45,
                'menu_id' => 3,
                'title' => '服務項目',
                'url' => '#',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2019-03-07 00:47:20',
                'updated_at' => '2019-03-07 00:47:20',
                'route' => NULL,
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 46,
                'menu_id' => 3,
                'title' => '聯絡我們',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2019-03-07 00:47:37',
                'updated_at' => '2019-03-07 00:47:37',
                'route' => 'contact-us',
                'parameters' => NULL,
            ),
            21 => 
            array (
                'id' => 47,
                'menu_id' => 3,
                'title' => 'FB專區',
                'url' => '#',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 18,
                'created_at' => '2019-03-07 00:47:55',
                'updated_at' => '2019-03-07 00:47:55',
                'route' => NULL,
                'parameters' => '',
            ),
            22 => 
            array (
                'id' => 48,
                'menu_id' => 3,
                'title' => '後台',
                'url' => 'admin',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 19,
                'created_at' => '2019-03-07 00:48:11',
                'updated_at' => '2019-05-05 16:14:36',
                'route' => NULL,
                'parameters' => '',
            ),
            23 => 
            array (
                'id' => 55,
                'menu_id' => 5,
                'title' => '首頁',
                'url' => '/',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-03-31 12:29:46',
                'updated_at' => '2019-03-31 12:38:44',
                'route' => NULL,
                'parameters' => '',
            ),
            24 => 
            array (
                'id' => 56,
                'menu_id' => 5,
                'title' => '教學文件',
                'url' => '/Documentation',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-03-31 12:30:07',
                'updated_at' => '2019-03-31 12:38:44',
                'route' => NULL,
                'parameters' => '',
            ),
            25 => 
            array (
                'id' => 57,
                'menu_id' => 5,
                'title' => 'Demo',
                'url' => '/demos',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-03-31 12:38:40',
                'updated_at' => '2019-03-31 12:38:44',
                'route' => NULL,
                'parameters' => '',
            ),
            26 => 
            array (
                'id' => 58,
                'menu_id' => 5,
                'title' => '古典',
                'url' => '/demo-agency.html',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 88,
                'order' => 1,
                'created_at' => '2019-03-31 12:39:28',
                'updated_at' => '2019-03-31 13:21:12',
                'route' => NULL,
                'parameters' => '',
            ),
            27 => 
            array (
                'id' => 59,
                'menu_id' => 5,
                'title' => 'App介紹',
                'url' => 'demo-app-landing.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 90,
                'order' => 1,
                'created_at' => '2019-03-31 12:45:52',
                'updated_at' => '2019-03-31 13:15:20',
                'route' => NULL,
                'parameters' => '',
            ),
            28 => 
            array (
                'id' => 60,
                'menu_id' => 5,
                'title' => '文章',
                'url' => 'demo-articles.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 88,
                'order' => 2,
                'created_at' => '2019-03-31 12:47:08',
                'updated_at' => '2019-03-31 13:21:12',
                'route' => NULL,
                'parameters' => '',
            ),
            29 => 
            array (
                'id' => 61,
                'menu_id' => 5,
                'title' => '髮廊',
                'url' => 'demo-barber.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 89,
                'order' => 1,
                'created_at' => '2019-03-31 12:48:00',
                'updated_at' => '2019-03-31 13:12:27',
                'route' => NULL,
                'parameters' => '',
            ),
            30 => 
            array (
                'id' => 62,
                'menu_id' => 5,
                'title' => 'SPA',
                'url' => 'demo-beauty.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 89,
                'order' => 2,
                'created_at' => '2019-03-31 12:49:16',
                'updated_at' => '2019-03-31 13:12:29',
                'route' => NULL,
                'parameters' => '',
            ),
            31 => 
            array (
                'id' => 63,
                'menu_id' => 5,
                'title' => '實體店面',
                'url' => 'demo-bike.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 89,
                'order' => 4,
                'created_at' => '2019-03-31 12:50:00',
                'updated_at' => '2019-03-31 13:21:25',
                'route' => NULL,
                'parameters' => '',
            ),
            32 => 
            array (
                'id' => 64,
                'menu_id' => 5,
                'title' => '生意',
                'url' => 'demo-business.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 90,
                'order' => 2,
                'created_at' => '2019-03-31 12:51:35',
                'updated_at' => '2019-03-31 13:15:20',
                'route' => NULL,
                'parameters' => '',
            ),
            33 => 
            array (
                'id' => 65,
                'menu_id' => 5,
                'title' => '咖啡店',
                'url' => 'demo-cafe.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 89,
                'order' => 5,
                'created_at' => '2019-03-31 12:52:40',
                'updated_at' => '2019-03-31 13:21:25',
                'route' => NULL,
                'parameters' => '',
            ),
            34 => 
            array (
                'id' => 66,
                'menu_id' => 5,
                'title' => '車行',
                'url' => 'demo-car.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 89,
                'order' => 6,
                'created_at' => '2019-03-31 12:53:19',
                'updated_at' => '2019-03-31 13:21:25',
                'route' => NULL,
                'parameters' => '',
            ),
            35 => 
            array (
                'id' => 67,
                'menu_id' => 5,
                'title' => '建築',
                'url' => 'demo-construction.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 92,
                'order' => 1,
                'created_at' => '2019-03-31 12:53:42',
                'updated_at' => '2019-03-31 13:19:14',
                'route' => NULL,
                'parameters' => '',
            ),
            36 => 
            array (
                'id' => 68,
                'menu_id' => 5,
                'title' => '課程',
                'url' => 'demo-course.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 90,
                'order' => 3,
                'created_at' => '2019-03-31 12:54:05',
                'updated_at' => '2019-03-31 13:15:20',
                'route' => NULL,
                'parameters' => '',
            ),
            37 => 
            array (
                'id' => 69,
                'menu_id' => 5,
                'title' => '電子商務',
                'url' => 'demo-ecommerce.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 89,
                'order' => 7,
                'created_at' => '2019-03-31 12:57:34',
                'updated_at' => '2019-03-31 13:21:25',
                'route' => NULL,
                'parameters' => '',
            ),
            38 => 
            array (
                'id' => 70,
                'menu_id' => 5,
                'title' => '健身房',
                'url' => 'demo-gym.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 89,
                'order' => 8,
                'created_at' => '2019-03-31 12:58:41',
                'updated_at' => '2019-03-31 13:21:25',
                'route' => NULL,
                'parameters' => '',
            ),
            39 => 
            array (
                'id' => 71,
                'menu_id' => 5,
                'title' => '3C',
                'url' => 'demo-headphones.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 90,
                'order' => 4,
                'created_at' => '2019-03-31 13:00:12',
                'updated_at' => '2019-03-31 13:14:46',
                'route' => NULL,
                'parameters' => '',
            ),
            40 => 
            array (
                'id' => 72,
                'menu_id' => 5,
                'title' => 'Hosting',
                'url' => 'demo-hosting.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 90,
                'order' => 5,
                'created_at' => '2019-03-31 13:00:44',
                'updated_at' => '2019-03-31 13:19:14',
                'route' => NULL,
                'parameters' => '',
            ),
            41 => 
            array (
                'id' => 74,
                'menu_id' => 5,
                'title' => '室內設計',
                'url' => 'demo-interior-design.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 92,
                'order' => 2,
                'created_at' => '2019-03-31 13:03:29',
                'updated_at' => '2019-03-31 13:19:14',
                'route' => NULL,
                'parameters' => '',
            ),
            42 => 
            array (
                'id' => 75,
                'menu_id' => 5,
                'title' => '醫學',
                'url' => 'demo-medical.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 90,
                'order' => 6,
                'created_at' => '2019-03-31 13:04:15',
                'updated_at' => '2019-03-31 13:19:14',
                'route' => NULL,
                'parameters' => '',
            ),
            43 => 
            array (
                'id' => 76,
                'menu_id' => 5,
                'title' => '現代Blog',
                'url' => 'demo-modern-blog.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 88,
                'order' => 3,
                'created_at' => '2019-03-31 13:04:51',
                'updated_at' => '2019-03-31 13:21:12',
                'route' => NULL,
                'parameters' => '',
            ),
            44 => 
            array (
                'id' => 77,
                'menu_id' => 5,
                'title' => '音樂',
                'url' => 'demo-music.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 90,
                'order' => 7,
                'created_at' => '2019-03-31 13:05:38',
                'updated_at' => '2019-03-31 13:19:14',
                'route' => NULL,
                'parameters' => '',
            ),
            45 => 
            array (
                'id' => 78,
                'menu_id' => 5,
                'title' => '新聞',
                'url' => 'demo-news.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 88,
                'order' => 4,
                'created_at' => '2019-03-31 13:06:05',
                'updated_at' => '2019-03-31 13:21:12',
                'route' => NULL,
                'parameters' => '',
            ),
            46 => 
            array (
                'id' => 79,
                'menu_id' => 5,
                'title' => '非營利組織',
                'url' => 'demo-nonprofit.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 90,
                'order' => 8,
                'created_at' => '2019-03-31 13:06:32',
                'updated_at' => '2019-03-31 13:18:16',
                'route' => NULL,
                'parameters' => '',
            ),
            47 => 
            array (
                'id' => 80,
                'menu_id' => 5,
                'title' => '寵物店',
                'url' => 'demo-pet.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 89,
                'order' => 9,
                'created_at' => '2019-03-31 13:07:40',
                'updated_at' => '2019-03-31 13:21:25',
                'route' => NULL,
                'parameters' => '',
            ),
            48 => 
            array (
                'id' => 81,
                'menu_id' => 5,
                'title' => '攝影',
                'url' => 'demo-photographer.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 91,
                'order' => 1,
                'created_at' => '2019-03-31 13:08:06',
                'updated_at' => '2019-03-31 13:18:29',
                'route' => NULL,
                'parameters' => '',
            ),
            49 => 
            array (
                'id' => 82,
                'menu_id' => 5,
            'title' => '攝影(深色)',
                'url' => 'demo-photographer-dark.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 91,
                'order' => 2,
                'created_at' => '2019-03-31 13:08:41',
                'updated_at' => '2019-03-31 13:18:33',
                'route' => NULL,
                'parameters' => '',
            ),
            50 => 
            array (
                'id' => 83,
                'menu_id' => 5,
                'title' => '攝影2',
                'url' => 'demo-photography.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 91,
                'order' => 3,
                'created_at' => '2019-03-31 13:09:22',
                'updated_at' => '2019-03-31 13:18:36',
                'route' => NULL,
                'parameters' => '',
            ),
            51 => 
            array (
                'id' => 84,
                'menu_id' => 5,
                'title' => '不動產',
                'url' => 'demo-real-estate.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 92,
                'order' => 3,
                'created_at' => '2019-03-31 13:09:53',
                'updated_at' => '2019-03-31 13:19:14',
                'route' => NULL,
                'parameters' => '',
            ),
            52 => 
            array (
                'id' => 85,
                'menu_id' => 5,
                'title' => '不動產2',
                'url' => 'demo-real-estate-2.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 92,
                'order' => 4,
                'created_at' => '2019-03-31 13:10:12',
                'updated_at' => '2019-03-31 13:19:14',
                'route' => NULL,
                'parameters' => '',
            ),
            53 => 
            array (
                'id' => 86,
                'menu_id' => 5,
                'title' => '不動產3',
                'url' => 'demo-real-estate-3.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 92,
                'order' => 5,
                'created_at' => '2019-03-31 13:10:38',
                'updated_at' => '2019-03-31 13:19:14',
                'route' => NULL,
                'parameters' => '',
            ),
            54 => 
            array (
                'id' => 87,
                'menu_id' => 5,
                'title' => '餐廳',
                'url' => 'demo-restaurant.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 89,
                'order' => 10,
                'created_at' => '2019-03-31 13:11:25',
                'updated_at' => '2019-03-31 13:21:25',
                'route' => NULL,
                'parameters' => '',
            ),
            55 => 
            array (
                'id' => 88,
                'menu_id' => 5,
                'title' => '經典',
                'url' => '#',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 111,
                'order' => 1,
                'created_at' => '2019-03-31 13:11:49',
                'updated_at' => '2019-03-31 13:11:59',
                'route' => NULL,
                'parameters' => '',
            ),
            56 => 
            array (
                'id' => 89,
                'menu_id' => 5,
                'title' => '熱門',
                'url' => '#',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 111,
                'order' => 2,
                'created_at' => '2019-03-31 13:12:14',
                'updated_at' => '2019-03-31 13:12:22',
                'route' => NULL,
                'parameters' => '',
            ),
            57 => 
            array (
                'id' => 90,
                'menu_id' => 5,
                'title' => '電子商務',
                'url' => '#',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 111,
                'order' => 3,
                'created_at' => '2019-03-31 13:13:41',
                'updated_at' => '2019-03-31 13:15:07',
                'route' => NULL,
                'parameters' => '',
            ),
            58 => 
            array (
                'id' => 91,
                'menu_id' => 5,
                'title' => '接案',
                'url' => '#',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 111,
                'order' => 4,
                'created_at' => '2019-03-31 13:16:03',
                'updated_at' => '2019-03-31 13:16:57',
                'route' => NULL,
                'parameters' => '',
            ),
            59 => 
            array (
                'id' => 92,
                'menu_id' => 5,
                'title' => '營造',
                'url' => '#',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 111,
                'order' => 5,
                'created_at' => '2019-03-31 13:16:46',
                'updated_at' => '2019-03-31 13:16:57',
                'route' => NULL,
                'parameters' => '',
            ),
            60 => 
            array (
                'id' => 93,
                'menu_id' => 5,
                'title' => '線上履歷',
                'url' => 'demo-resume.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 88,
                'order' => 5,
                'created_at' => '2019-03-31 13:18:56',
                'updated_at' => '2019-03-31 13:21:12',
                'route' => NULL,
                'parameters' => '',
            ),
            61 => 
            array (
                'id' => 94,
                'menu_id' => 5,
                'title' => 'SEO',
                'url' => 'demo-seo.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 91,
                'order' => 4,
                'created_at' => '2019-03-31 13:19:29',
                'updated_at' => '2019-03-31 13:21:13',
                'route' => NULL,
                'parameters' => '',
            ),
            62 => 
            array (
                'id' => 95,
                'menu_id' => 5,
                'title' => '商店',
                'url' => 'demo-shop.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 89,
                'order' => 11,
                'created_at' => '2019-03-31 13:19:46',
                'updated_at' => '2019-03-31 13:21:25',
                'route' => NULL,
                'parameters' => '',
            ),
            63 => 
            array (
                'id' => 96,
                'menu_id' => 5,
                'title' => 'Spa 2',
                'url' => 'demo-spa.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 89,
                'order' => 3,
                'created_at' => '2019-03-31 13:20:08',
                'updated_at' => '2019-03-31 13:21:25',
                'route' => NULL,
                'parameters' => '',
            ),
            64 => 
            array (
                'id' => 97,
                'menu_id' => 5,
                'title' => '旅遊',
                'url' => 'demo-travel.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 92,
                'order' => 6,
                'created_at' => '2019-03-31 13:20:26',
                'updated_at' => '2019-03-31 13:21:31',
                'route' => NULL,
                'parameters' => '',
            ),
            65 => 
            array (
                'id' => 98,
                'menu_id' => 5,
                'title' => '寫作',
                'url' => 'demo-writer.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 88,
                'order' => 6,
                'created_at' => '2019-03-31 13:20:43',
                'updated_at' => '2019-03-31 13:21:39',
                'route' => NULL,
                'parameters' => '',
            ),
            66 => 
            array (
                'id' => 99,
                'menu_id' => 5,
                'title' => '聖誕',
                'url' => 'demo-xmas.html',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 88,
                'order' => 7,
                'created_at' => '2019-03-31 13:21:02',
                'updated_at' => '2019-03-31 13:21:45',
                'route' => NULL,
                'parameters' => '',
            ),
            67 => 
            array (
                'id' => 100,
                'menu_id' => 6,
                'title' => '首頁',
                'url' => '#wrapper',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-04-04 22:01:42',
                'updated_at' => '2019-04-04 22:08:39',
                'route' => NULL,
                'parameters' => '',
            ),
            68 => 
            array (
                'id' => 101,
                'menu_id' => 6,
                'title' => '探索',
                'url' => '#section-nextgen',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-04-04 22:02:42',
                'updated_at' => '2019-04-07 20:20:04',
                'route' => NULL,
                'parameters' => '',
            ),
            69 => 
            array (
                'id' => 102,
                'menu_id' => 6,
                'title' => '次世代網頁後台',
                'url' => '#section-nextgen',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 101,
                'order' => 1,
                'created_at' => '2019-04-04 22:03:13',
                'updated_at' => '2019-04-07 20:19:24',
                'route' => NULL,
                'parameters' => '',
            ),
            70 => 
            array (
                'id' => 103,
                'menu_id' => 6,
                'title' => '驚人的視覺',
                'url' => '#section-stunning-graphics',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 101,
                'order' => 2,
                'created_at' => '2019-04-04 22:03:34',
                'updated_at' => '2019-04-07 20:19:43',
                'route' => NULL,
                'parameters' => '',
            ),
            71 => 
            array (
                'id' => 104,
                'menu_id' => 6,
                'title' => '支持手機版',
                'url' => '#section-secured-solutions',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 101,
                'order' => 3,
                'created_at' => '2019-04-04 22:03:53',
                'updated_at' => '2019-04-07 20:19:56',
                'route' => NULL,
                'parameters' => '',
            ),
            72 => 
            array (
                'id' => 105,
                'menu_id' => 6,
                'title' => '價格',
                'url' => '#section-pricing',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-04-04 22:04:12',
                'updated_at' => '2019-04-07 20:20:12',
                'route' => NULL,
                'parameters' => '',
            ),
            73 => 
            array (
                'id' => 108,
                'menu_id' => 7,
                'title' => '常見問題',
                'url' => '#section-faqs',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-04-04 22:19:11',
                'updated_at' => '2019-08-24 15:13:19',
                'route' => NULL,
                'parameters' => '',
            ),
            74 => 
            array (
                'id' => 109,
                'menu_id' => 7,
                'title' => '軟體畫面',
                'url' => '#section-gallery',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-04-04 22:19:29',
                'updated_at' => '2019-08-24 15:13:19',
                'route' => NULL,
                'parameters' => '',
            ),
            75 => 
            array (
                'id' => 110,
                'menu_id' => 7,
                'title' => '登入',
                'url' => '#modal-login',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-04-04 22:19:54',
                'updated_at' => '2019-08-24 15:13:19',
                'route' => NULL,
                'parameters' => '',
            ),
            76 => 
            array (
                'id' => 111,
                'menu_id' => 6,
                'title' => '範例網頁',
                'url' => '#',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-04-16 20:57:08',
                'updated_at' => '2019-04-16 21:05:53',
                'route' => NULL,
                'parameters' => '',
            ),
            77 => 
            array (
                'id' => 114,
                'menu_id' => 1,
                'title' => '使用者',
                'url' => '/admin/users',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => 3,
                'order' => 1,
                'created_at' => '2019-07-31 09:13:52',
                'updated_at' => '2019-07-31 09:14:01',
                'route' => NULL,
                'parameters' => '',
            ),
            78 => 
            array (
                'id' => 115,
                'menu_id' => 7,
                'title' => '聯絡我們',
                'url' => '/contact',
                'target' => '_blank',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-08-24 15:13:15',
                'updated_at' => '2019-08-24 15:13:19',
                'route' => NULL,
                'parameters' => '',
            ),
            79 => 
            array (
                'id' => 116,
                'menu_id' => 1,
                'title' => '商品集',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-gift',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 20,
                'created_at' => '2019-11-10 18:55:26',
                'updated_at' => '2019-11-10 18:55:26',
                'route' => 'voyager.items.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}